travelnest/booking/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('book_homestay/<int:homestay_id>/', views.book_homestay, name='book_homestay'),
    path('homestay/<int:homestay_id>/add_review/', views.add_review, name='add_review'),
    path('initiate',views.initkhalti,name="initiate"),
    path('verify_payment/', views.verify_payment, name='verify_payment'),
    path('store-booking-data/', views.store_booking_data, name='store_booking_data'),
    path('all_bookings/', views.all_bookings, name='all_bookings'),
]

travelnest/chatbot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/', views.chat, name='chat'),
    path('chatbot/', views.chatbot, name='chatbot'),
]

travelnest/travelnest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
from contents import views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('',views.show_home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('hosting/', include('hosting.urls')),
    path('homestay/', include('homestay.urls')),
    path('custom-admin/', include('custom_admin.urls')),
    path('booking/', include('booking.urls')),
    path('chatbot/', include('chatbot.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelnest/booking/models.py
from django.db import models
from homestay.models import HomeStay
from django.conf import settings

# Create your models here.


class Booking(models.Model):
    PAYMENT_CHOICES = [
        ('Khalti', 'Khalti'),
        ('Pay on Arrival', 'Pay on Arrival'),
    ]

    homestay = models.ForeignKey(HomeStay, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    num_guests = models.IntegerField()
    amount = models.IntegerField()
    payment_type = models.CharField(max_length=20, choices=PAYMENT_CHOICES)


class Review(models.Model):
    homestay = models.ForeignKey(HomeStay, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.rating} stars"

travelnest/chatbot/models.py
from django.db import models

# Create your models here.

travelnest/booking/views.py
import json

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.html import strip_tags
from django.views.decorators.csrf import csrf_exempt

from homestay.models import HomeStay

from .models import Booking, Review
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.sessions.models import Session
from django.contrib import messages

# Create your views here.


@login_required
def book_homestay(request, homestay_id):
    homestay = get_object_or_404(HomeStay, id=homestay_id)
    user = request.user

    if user.is_authenticated:
        if user.is_host:
            # If user is a host, display error message
            messages.error(request, 'You are logged in as a host.')
            return redirect('detail', homestay_id=homestay.id)
        else:
            # User is a guest, allow booking
            if request.method == 'POST':
                # Process form submission
                check_in_date = request.POST.get('formatted_check_in_date')
                check_out_date = request.POST.get('formatted_check_out_date')
                num_guests = int(request.POST.get('num_guests'))
                totalAmount = request.POST.get('totalAmount') 
                payment_type = request.POST.get('payment_option')

                # Perform validation as needed
                if check_in_date and check_out_date and num_guests and payment_type:
                    # Convert num_guests to an integer
                    num_guests = int(num_guests)

                    # Create a new booking instance and save it
                    booking = Booking.objects.create(
                        homestay=homestay,
                        user=user,
                        check_in_date=check_in_date,
                        check_out_date=check_out_date,
                        num_guests=num_guests,
                        amount=totalAmount,
                        payment_type=payment_type
                    )
                    # Proceed with booking or display confirmation
                    messages.success(request, 'Booking successful!')

                    # # Send confirmation email to the user
                    # subject = 'Homestay Booking Confirmation'
                    # html_message = render_to_string('booking_confirmation_email.html', {'homestay': homestay, 'booking': booking})
                    # plain_message = strip_tags(html_message)
                    # send_mail(subject, plain_message, settings.EMAIL_HOST_USER, [request.user.email], html_message=html_message)
                    return redirect('detail', homestay_id=homestay.id)
                else:
                    # Handle invalid form data
                    messages.error(request, 'Invalid form data. Please fill in all fields.')
                    return redirect('detail', homestay_id=homestay.id)
            else:
                return render(request, 'detail.html', {'homestay': homestay})
    else:
        # If user is not authenticated, display error message
        messages.error(request, 'You must be logged in to book a homestay.')
        return render(request, 'detail.html', {'homestay': homestay})
    
def add_review(request, homestay_id):
    today = timezone.now().date()
    print("Today's Date:", today)

    homestay = get_object_or_404(HomeStay, id=homestay_id)

    user_has_booked_homestay = Booking.objects.filter(
    homestay=homestay,
    user=request.user,

    ).exists()

    if request.method == 'POST':
        rating = request.POST.get('rating')
        comment = request.POST.get('comment')

        if request.user.is_authenticated and user_has_booked_homestay:
            Review.objects.create(
                homestay=homestay,
                user=request.user,
                rating=rating,
                comment=comment
            )
            messages.success(request, 'Review submitted successfully.')
            return redirect('detail', homestay_id=homestay.id)
        else:
            messages.error(request, 'Unable to submit the review.')
            return redirect('detail', homestay_id=homestay.id)

    reviews = Review.objects.filter(homestay=homestay).order_by('-created_at')
    # Inside the add_review view
    print("User has booked homestay:", user_has_booked_homestay)


    return render(request, 'detail.html', {'homestay': homestay, 'reviews': reviews, 'user_has_booked_homestay': user_has_booked_homestay})

@csrf_exempt
def initkhalti(request):
    if request.method == 'POST':
        url = "https://a.khalti.com/api/v2/epayment/initiate/"
        return_url = request.POST.get('return_url')
        amount = request.POST.get('amount')
        purchase_order_id = request.POST.get('purchase_order_id')
        host_user = request.POST.get('host_user')
        host_email = request.POST.get('host_email')
        host_mobile = request.POST.get('host_mobile')
        homestay = request.POST.get('homestay_name')
        homestay_id = request.POST.get('homestay_id')
        check_in_date = request.POST.get('check_in')
        check_out_date = request.POST.get('check_out')
        num_guests = request.POST.get('num_guest')
        payment_type = request.POST.get('payment_type')
        
        # Store values in session
        request.session['host_name'] = host_user
        request.session['host_email'] = host_email
        request.session['check_in_date'] = check_in_date
        request.session['check_out_date'] = check_out_date
        request.session['num_guests'] = num_guests
        request.session['total_amount'] = amount
        request.session['payment_type'] = payment_type
        request.session['homestay_id'] = homestay_id

        user=request.user
        print("return_url",return_url)
        print("amount",amount)
        print("purchase_order_id",purchase_order_id)
        payload = json.dumps({
        "return_url": return_url,
        "website_url" : "http://127.0.0.1:8000",
        "amount": amount,
        "purchase_order_id": purchase_order_id,
        "purchase_order_name": "test",
        "customer_info": {
            "name": host_mobile,
        }
        })

        headers = {
    'Authorization': 'key f6a457f2166d415e9172144907325c3d',
        'Content-Type': 'application/json',
    }

        response = requests.post(url, headers=headers, data=payload)
        print(response.text)
        new_res =json.loads(response.text)

        print(new_res)
        return redirect(new_res['payment_url'])
    

    




def verify_payment(request):
    url = "https://a.khalti.com/api/v2/epayment/lookup/"
    if request.method == 'GET':
        headers = {
            'Authorization': 'key f6a457f2166d415e9172144907325c3d',
            'Content-Type': 'application/json',
        }
        pidx = request.GET.get('pidx')
        data = json.dumps({
            'pidx':pidx
        })
        res = requests.request('POST',url,headers=headers,data=data)
        print(res)
        print(res.text)

        new_res = json.loads(res.text)
        print(new_res)
        

        if new_res['status'] == 'Completed':
            host_name = request.session.get('host_name')
            host_email = request.session.get('host_email')
            check_in_date = request.session.get('check_in_date')
            check_out_date = request.session.get('check_out_date')
            num_guests = request.session.get('num_guests')
            total_amount = request.session.get('total_amount')
            payment_type = request.session.get('payment_type')
            homestay_id = request.session.get('homestay_id')
            user = request.user
            homestay = get_object_or_404(HomeStay, id=homestay_id)
            # user.has_verified_dairy = True
            # user.save()
            # perform your db interaction logic
            booking = Booking.objects.create(
                homestay=homestay,
                user=user,
                check_in_date=check_in_date,
                check_out_date=check_out_date,
                num_guests=num_guests,
                amount=total_amount,
                payment_type=payment_type
            )
            messages.success(request, 'You have booked successfully')
            return redirect('home')
        
        # else:
        #     # give user a proper error message
        #     raise BadRequest("sorry ")

        return redirect('home')



def store_booking_data(request):
    if request.method == 'POST':
        booking_data = request.POST.get('booking_data')
        request.session['booking_data'] = booking_data
        return JsonResponse({'message': 'Booking data stored successfully.'})
    else:
        return JsonResponse({'error': 'Invalid request method.'}, status=400)
    


def all_bookings(request):
    bookings = Booking.objects.all()
    return render(request, 'all_bookings.html', {'bookings': bookings})

travelnest/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block extrastyle %}
<link href="{% static 'css/style1.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
<div class="container">
    <br>
    <center>
        <h1>ABOUT US</h1>
        <br>
    </center>
    <div style="text-align: center;">
        <img src="{% static 'images/about.jpg' %}" alt="image">
    </div>
    <br><br>
    <p style="font-size:160%;">
        At TravelNest, we believe in the warmth of home, the richness of cultural exchange, and the joy of connecting
        with fellow travelers. Our platform is not just about providing a place to stay; it's about creating an
        immersive and authentic experience that goes beyond the ordinary.
        TravelNest is a platform for hosts to rent out their rooms to tourists seeking unique and personalized
        accommodations. Hosts can list their available rooms, set pricing, and efficiently manage bookings. Travelers
        can discover and book homestays that match their preferences, budget, and desired location.

        <br><br><br>
        <b>Our Hosts</b><br>
        Our hosts are the heartbeat of our community. Handpicked for their warmth,
        hospitality, and genuine love for sharing their culture, they take pride in offering more than just a place to
        sleep.
        Expect personalized recommendations, home-cooked meals, and insights into local life that you won't find in any
        guidebook. <br><br><br>
      <b>  Diversity and Inclusivity</b><br>
        We celebrate diversity and believe in the power of inclusivity. Our homestays are as diverse as our global
        community of travelers. From bustling city apartments to serene countryside retreats, each homestay reflects the
        unique flavor of its location, ensuring a truly enriching experience for our guests.
<br><br>
      <b>  A Commitment to Quality</b><br>
        Quality is non-negotiable for us. We meticulously vet each homestay to ensure it meets our high standards of
        cleanliness, comfort, and safety. Our commitment to quality extends to every aspect of your experience, from
        user-friendly booking processes to responsive customer support.
    </p>
</div>
<div>

</div>
{% endblock %}

travelnest/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="form-main">
    <div class="form">
        <div class="form-title">Add Homestay</div>
        <div class="form-content">
            <form action="{% url 'add_homestay' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="user-details">
                    <div class="input-box">
                        <span class="details">Name</span>
                        <input type="text" name="name" placeholder="Enter the name of the homestay." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Location</span>
                        <input type="text" name="location" placeholder="Enter its location." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Number of Guests</span>
                        <input type="number" name="num_guests" placeholder="Enter no. of guests." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Price per Night</span>
                        <input type="number" name="price_per_night" placeholder="Enter price per night." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Ownership Documents</span>
                        <input type="file" name="ownership_documents" placeholder="Upload a copy of ownership documents." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Citizenship Documents</span>
                        <input type="file" name="citizenship_documents" placeholder="Upload a copy of your citizenhip." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Thumbnail Image</span>
                        <input type="file" name="thumbnail_image" placeholder="Upload thumbnail image." required>
                    </div>
                    <div class="input-box">
                        <span class="details">Secondary Image Image</span>
                        <input type="file" name="secondary_images" placeholder="Upload secondary images." multiple required>
                    </div>
                    <div class="input-box">
                        <span class="details">Description</span>
                        <textarea name="description" placeholder="Description of homestay." required></textarea>
                    </div>
                    <div class="">
                        <span class="details">Features</span>
                        {% for category, features in organized_features.items %}
                            <div class="category">
                                <h3>{{ category }}</h3>
                                <ul>
                                    {% for feature in features %}
                                        <li>
                                            <input type="checkbox" name="features" value="{{ feature.id }}">
                                            <span>{{ feature.name }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                    {% endfor %}
                    </div>
                </div>
                <div>
                    <div>Select Location</div>
                    <div id="map" style="height: 400px; z-index: 0;"></div>
                    <!-- Hidden form fields to store latitude and longitude -->
                    <input type="hidden" id="latitude" name="latitude">
                    <input type="hidden" id="longitude" name="longitude">
                    </div>
                <div class="button">
                    <input type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>


<script>


    document.addEventListener('DOMContentLoaded', function () {
        const form = document.querySelector('.form form');
        const name = document.querySelector('input[name="name"]');
        const location = document.querySelector('input[name="location"]');
        const numGuests = document.querySelector('input[name="num_guests"]');
        const pricePerNight = document.querySelector('input[name="price_per_night"]');

        form.addEventListener('submit', function (event) {
            event.preventDefault();

            // Regular expressions for numeric values
            const numRegex = /^[0-9]+$/;

            // Validation checks
            if (!name.value.trim()) {
                alert("Name is required.");
                return;
            }
            if (!location.value.trim()) {
                alert("Location is required.");
                return;
            }
            if (!numGuests.value.trim()) {
                alert("Number of guests is required.");
                return;
            }
            if (!numRegex.test(numGuests.value.trim())) {
                alert("Number of guests must contain only numeric values.");
                return;
            }
            if (!pricePerNight.value.trim()) {
                alert("Price per night is required.");
                return;
            }
            if (isNaN(pricePerNight.value.trim())) {
                alert("Price per night must contain only numeric values.");
                return;
            }

            // If all validations pass, submit the form
            form.submit();
        });
    });


    var map = L.map('map').setView([28.3949, 84.124], 7); // Set initial coordinates and zoom level for Nepal
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map); // Add base tile layer

    var marker;
    var searchMarker; // Reference to the search marker
    map.on('click', function(e) {
        if (searchMarker) {
            map.removeLayer(searchMarker); // Remove the search marker if it exists
        }
        if (marker) {
            map.removeLayer(marker);
        }
        marker = L.marker(e.latlng).addTo(map);
        // Retrieve latitude and longitude of the selected location and store it in hidden form fields
        document.getElementById('latitude').value = e.latlng.lat;
        document.getElementById('longitude').value = e.latlng.lng;
    });

    // Start adding controls as follow... L.controlName().addTo(map);
    // Control 1: This add the OpenStreetMap background tile
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // Control 2: This add a scale to the map
    L.control.scale().addTo(map);

    // Control 3: This add a Search bar
    var searchControl = new L.esri.Controls.Geosearch().addTo(map);
    var results = new L.LayerGroup().addTo(map);

    searchControl.on('results', function(data){
        results.clearLayers();
        for (var i = data.results.length - 1; i >= 0; i--) {
            searchMarker = L.marker(data.results[i].latlng).addTo(map); // Store the search marker reference
            results.addLayer(searchMarker);
        }
    });

    
</script>


{% endblock %}

travelnest/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 60%;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        cursor: pointer;
    }

    .close:hover {
        color: black;
    }

    .confirmation-container {
        text-align: center;
    }

    #confirmationDetails {
        font-size: 16px;
        margin-bottom: 20px;
    }

    .button-container {
        justify-content: center;
    }

    .btn {
        margin: 0 10px;
    }
</style>
<div class="container-fluid main-content" style="margin-top: 65px;">
    <div style="display: flex; justify-content: center; margin-left: 105px;">
        <div>
            <img src="{{ homestay.thumbnail_image.url }}" class="mb-4" alt="{{ homestay.name }}" style="height: 65vh; width: 45vw; margin-right: 25px;">
        </div>
        <div>
            {% if homestay.images.all %}
                <div style="display: flex; flex-wrap: wrap; width: 50vw;">
                    {% for image in homestay.images.all %}
                        <div style="margin-bottom: 25px; margin-right: 15px;">
                            <img src="{{ image.image.url }}" class="img-fluid" alt="Secondary Image" style="height: 31vh; width: 20vw; object-fit: cover;">
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    <div class="container mt-5" style="display: flex; justify-content: space-between">
        <div>
            <h2 class="mt-3 mb-3">{{ homestay.name }} </h2>
            <p><strong>Location:</strong> {{ homestay.location }}</p>
            <p><strong>Price:</strong> Rs. {{ homestay.price_per_night }}/ night</p>
            <p><strong>Number of Guests:</strong> {{ homestay.num_guests }}</p>
            <p><strong>Hosted By:</strong> {{ homestay.host}}</p>
        </div>
        <div style="width: 35vw;">
            <h4>About</h4>
            <p>{{ homestay.description }}</p>
        </div>
    </div>

    <div class="container mt-5" style="display: flex; justify-content: space-between;">
        <div>
            {% if homestay.features.all %}
                <h4 class="mt-4">Features</h4>
                <ul>
                    {% for feature in homestay.features.all %}
                        <li>{{ feature.name }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div style="border: 1px solid gray; border-radius: 25px; padding: 25px;">
            <h4 class="mt-4">Book Now</h4>
            <form id="bookingForm" method="post" action="{% url 'homestay_details' homestay.id %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="check_in_date">Check-in Date:</label>
                    <input type="date" name="check_in_date" id="id_check_in_date" min="{% now 'Y-m-d' %}" required onchange="updateCheckoutDates()"><br/>
                </div>
                <div class="mb-3">
                    <label for="check_out_date">Check-out Date:</label>
                    <input type="date" name="check_out_date" id="id_check_out_date" min="{% now 'Y-m-d' %}" required><br/>
                </div>
                <div class="mb-3">
                    <label for="num_guests">Number of Guests:</label>
                    <input type="number" name="num_guests" id="id_num_guests" required><br/>
                </div>
                <div class="form-field">
                    <label for="paymentMethod">Payment Method</label>
                    <select name="paymentMethod" class="form1" id="id_paymentmethod">
                        <option value="khalti">Khalti</option>
                        <option value="arrival">Pay on Arrival</option>
                    </select>
                </div>
                <button type="button" id="payment-button" onclick="displayConfirmation()" class="btn btn-primary mt-3">Book Now</button>
            </form>
        </div>
    </div>

    <div class="container" style="margin-top: 20vh;">
        {% if request.user.is_authenticated and user_has_booked_homestay %}
            <h4 class="mt-4">Add Your Review</h4>
            <form method="post" action="{% url 'add_review' homestay.id %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="rating">Rating (1-5):</label>
                    <input type="number" name="rating" id="id_rating" min="1" max="5" required><br/>
                </div>
                <div class="mb-3">
                    <label for="comment">Your Comment:</label>
                    <textarea name="comment" id="id_comment" rows="4" required></textarea><br/>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Submit Review</button>
            </form>
        {% endif %}
    </div>

    <div class="container" style="margin-top: 20vh;">
        <h4 class="mt-4">Reviews and Ratings</h4>
        <ul>
            {% for review in reviews %}
                <div class="card" style="padding: 25px;">
                    <div style="display: flex;">
                        <div style="margin-right: 60px;">
                            {{ review.user.username }}
                        </div>
                        <div>
                            <div>{{ review.rating }} <i class="bi-star-fill"></i> </div>
                        </div>
                    </div>
                    <div style="display: flex; justify-content: space-between;">
                        <div>
                            {{ review.comment }}
                        </div>
                        <div>{{ review.created_at }}</div>
                    </div>
                </div>
            {% endfor %}
        </ul>
    </div>

    <div id="confirmationPopup" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeConfirmationPopup()">&times;</span>
            <p id="confirmationDetails">Booking confirmation details go here...</p>
            <div id="paymentForm"></div>

            <button onclick="confirmBooking()">Confirm</button>
        </div>
    </div>
</div>

<script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>

<script>
    const csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;

    function displayConfirmation() {
        const checkInDate = document.getElementById('id_check_in_date').value;
        const checkOutDate = document.getElementById('id_check_out_date').value;
        const numGuests = document.getElementById('id_num_guests').value;
        const paymentmethod = document.getElementById('id_paymentmethod').value;

        if (!checkInDate || !checkOutDate || !numGuests || !paymentmethod) {
            alert('Please fill in all the required fields.');
            return;
        }

        const confirmationPopup = document.getElementById('confirmationPopup');
        const confirmationDetails = document.getElementById('confirmationDetails');
        confirmationDetails.innerText = `Check-in Date: ${checkInDate}\nCheck-out Date: ${checkOutDate}\nNumber of Guests: ${numGuests}\nPayment Method: ${paymentmethod}`;
        confirmationPopup.style.display = 'block';

        if (paymentmethod === 'khalti') {
        
            const paymentForm = `
                <form id="khaltiForm" action="{% url 'initiate' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="purchase_order_id" value="1" id="pid">
                    <input type="hidden" name="amount" value= "{{ homestay.price_per_night }}" id="amt">
                    <input type="hidden" name="return_url" value="http://127.0.0.1:8000/verify_payment">
                    <button type="submit">Pay With Khalti</button>
                </form>
            `;
            document.getElementById('paymentForm').innerHTML = paymentForm;
        }
    }
    
    

    function confirmBooking() {
        const paymentmethod = document.getElementById('id_paymentmethod').value;

        if (paymentmethod === 'khalti') {
            
            alert('Payment with Khalti successful. Booking confirmed.');

        } else if (paymentmethod === 'arrival') {
        
        
            alert('Payment with Khalti successful. Booking confirmed.');

        };

    document.getElementById('bookingForm').submit();
}


    function verifyPayment(payload) {
        $.ajax({
            url: "{% url 'verify_payment' %}",
            type: "POST",
            data: payload,
            dataType: 'json',
            success: function (response) {
                if (response.status === 'success') {
                    alert(response.message);
                } else {
                    alert(response.message);
                }
            },
            error: function (error) {
                alert('Error verifying payment.');
                console.log(error);
            }
        });
    }

</script>

{% endblock %}